name: Update Semantic Version on PR Sync

on:
  pull_request:
    branches:
      - dev
    types:
      - synchronize
      - opened

env:
  DEFAULT_VERSION: "1.0.0"
  VERSION_PATTERN: '^[0-9]+\.[0-9]+\.[0-9]+$'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch and Parse Previous Version Labels
        id: versioning
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name: $BRANCH_NAME"

          # Fetch all PR labels that match semantic version pattern
          all_labels=$(gh pr list --state all --json labels --jq '.[].labels[].name' | grep -E '${{ env.VERSION_PATTERN }}' || true)

          if [[ -n "$all_labels" ]]; then
            echo "$all_labels" | sort -V | tee sorted_versions.txt
            LATEST_VERSION=$(tail -n 1 sorted_versions.txt)
          else
            echo "No matching version labels found. Using default."
            LATEST_VERSION="${{ env.DEFAULT_VERSION }}"
          fi

          echo "Latest version: $LATEST_VERSION"

          # Split version into components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_VERSION"

          # Normalize branch name
          BRANCH_NAME_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')

          # Versioning logic based on branch type
          if [[ "$BRANCH_NAME_LOWER" == *major* ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [[ "$BRANCH_NAME_LOWER" == *minor* ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Label if it Doesn't Exist
        run: |
          label_exists=$(gh label list --repo ${{ github.repository }} | grep -qw "${{ env.NEW_VERSION }}" || echo "not_found")
          if [[ "$label_exists" == "not_found" ]]; then
            echo "Creating label: ${{ env.NEW_VERSION }}"
            gh label create "${{ env.NEW_VERSION }}" --description "Auto-generated version label" --force
          else
            echo "Label already exists: ${{ env.NEW_VERSION }}"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add Label to PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ env.NEW_VERSION }}
